version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"